### ISSUE TITLE
Allow scan in user's setting doesn't appear...

### ISSUE THREAD

**Issue by inakifeliu** [matiasdelellis/facerecognition#166]
On Debian 10 and nextcloud 17, no option appears to allow image scan in user's settings, it's in blank...

![Captura de pantalla (76)](https://user-images.githubusercontent.com/2342439/67051891-c069c600-f13c-11e9-9b51-eb571a12f14e.png)
 
I attach the configuration section in case is needed.
![Captura de pantalla (77)](https://user-images.githubusercontent.com/2342439/67051971-0aeb4280-f13d-11e9-89e6-dc17e2e7310c.png)

Thanks in advance!

**Comment by matiasdelellis** [comment]
Hi @inakifeliu 
Please verify in the browser inspector that there are no errors..  also in the nextcloud log after accessing this page...

Then verify that you installed all the dependencies..
(Inside the app/facerecognition/ folder, do a `make build` and show us the result.)

**Comment by inakifeliu** [comment]
Hi,
Thanks for your quick reply.
I've found some errors with the handlbears runtime:
![Captura de pantalla (78)](https://user-images.githubusercontent.com/2342439/67100199-88579700-f1bf-11e9-85d1-c4436177b425.png)

  // Use the embedded version info since the runtime doesn't know about this revision yet
	      throw new _exception2['default']('Template was precompiled with a newer version of Handlebars than the current runtime. ' + 'Please update your runtime to a newer version (' + compilerInfo[1] + ').');

And here you have the make build output:

root@nextcloud .../apps/facerecognition# make build
Checking binaries needed to build the application
Testing curl, wget and bzip2. If one is missing, install it with the tools of your system.
curl -V
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
wget -V
GNU Wget 1.20.1 built on linux-gnu.

-cares +digest -gpgme +https +ipv6 +iri +large-file -metalink +nls 
+ntlm +opie +psl +ssl/gnutls 

Wgetrc: 
    /etc/wgetrc (system)
Locale: 
    /usr/share/locale 
Compile: 
    gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc" 
    -DLOCALEDIR="/usr/share/locale" -I. -I../../src -I../lib 
    -I../../lib -Wdate-time -D_FORTIFY_SOURCE=2 
    -I/usr/include/p11-kit-1 -DHAVE_LIBGNUTLS -DNDEBUG -g -O2 
    -fdebug-prefix-map=/build/wget-EiPT9d/wget-1.20.1=. 
    -fstack-protector-strong -Wformat -Werror=format-security 
    -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall 
Link: 
    gcc -I/usr/include/p11-kit-1 -DHAVE_LIBGNUTLS -DNDEBUG -g -O2 
    -fdebug-prefix-map=/build/wget-EiPT9d/wget-1.20.1=. 
    -fstack-protector-strong -Wformat -Werror=format-security 
    -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall -Wl,-z,relro -Wl,-z,now 
    -lpcre2-8 -luuid -lidn2 -lnettle -lgnutls -lz -lpsl ftp-opie.o 
    gnutls.o http-ntlm.o ../lib/libgnu.a 

Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.
Testing handlebars needed to compile the templates. If it fails install as:
 # sudo npm install handlebars -g
handlebars -v
4.4.3
composer install --prefer-dist
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
composer update --prefer-dist
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
handlebars js/templates -f js/templates.js
Build done. You can enable the application in Nextcloud.


Thanks!

**Comment by matiasdelellis** [comment]
https://github.com/nextcloud/server/pull/17255

However, this project downloads its own version of handlebars .. :confused: 

Now clean my repo and build again to test..

**Comment by matiasdelellis** [comment]
Ok ok..
I reproduced the problem ... :disappointed: 

To continue momentarily force an earlier version of handlebars and rebuild template.. 

```
[matias@nube facerecognition]$ sudo npm install handlebars@4.1.2 -g
/usr/bin/handlebars -> /usr/lib/node_modules/handlebars/bin/handlebars
+ handlebars@4.1.2
updated 1 package in 0.965s
[matias@nube facerecognition]$ handlebars -v
4.1.2
[matias@nube facerecognition]$ make js-templates 
handlebars js/templates -f js/templates.js
[matias@nube facerecognition]$ 
```

Then I see how to fix it definitely .. .

**Comment by inakifeliu** [comment]
I've done all the steps you've made, but I still getting the same error.
I've made a make, and restarted php and apache2.
Thanks...

**Comment by matiasdelellis** [comment]
Hi @inakifeliu 
Sorry the delay.. :sweat_smile: 

Please, first verify this:

> [matias@nube facerecognition]$ handlebars -v
> 4.1.2

... and show me the screenshot of inspector again to known if it's the same error.

Also do a 'make clean' before do 'make'

**Comment by matiasdelellis** [comment]
Hi,
I understand that this report was resolved, and I close it. Please, if necessary, open it again. :smile:

**Comment by joao-p-marques** [comment]
Hi! I am still getting this issue with Nextcloud 21, and following your steps didn't help.
I also can't set any of the values in settings in the admin part:
![image](https://user-images.githubusercontent.com/38977934/113506764-adb89c00-953e-11eb-8ad2-e42cfeb28ef0.png)

Can this be reopened?
