### ISSUE TITLE
Unhandled exception and Albums are not being created 

### ISSUE THREAD

**Issue by teclab-at** [matiasdelellis/facerecognition#634]
### Expected behaviour

I'd expect new albums per detected face.

### Actual behaviour

No albums are being created.
Well ... it worked once, until I reset my faces and deleted all albums manually.

### Steps to reproduce

```
sudo -u www-data /usr/bin/php /var/www/nextcloud/occ face:sync-albums
Synchronizing albums for the user <>. An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\FaceRecognition\Helper\PhotoAlbums::syncUser() must be of the type string, null given, called in /var/www/nextcloud/apps/facerecognition/lib/Command/SyncAlbumsCommand.php on line 119 and defined in /var/www/nextcloud/apps/facerecognition/lib/Helper/PhotoAlbums.php:67
Stack trace:
#0 /var/www/nextcloud/apps/facerecognition/lib/Command/SyncAlbumsCommand.php(119): OCA\FaceRecognition\Helper\PhotoAlbums->syncUser()
#1 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\SyncAlbumsCommand->execute()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#5 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#6 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#7 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```

There is no error when passing a name:
```
sudo -u www-data /usr/bin/php -f /var/www/nextcloud/occ face:sync-albums -u Thomas
Synchronizing albums for the user <Thomas>. Done.
```
Still there are no albums created.

* **Operating system:**

```
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

* **PHP version:**

`PHP 7.4.33 (cli) (built: Nov  8 2022 11:40:37) ( NTS )`

* **Web server:**

```
Server version: Apache/2.4.54 (Debian)
Server built:   2022-06-09T04:26:43
```

* **Nextcloud version:**

`[Nextcloud Hub 3](https://nextcloud.com/) (25.0.3)`

### Logs

No server logs available - clean.

**Comment by pmduque** [comment]
Same is happening to me.

**Comment by Tirpitz93** [comment]
Same issue here.
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
PHP
```

[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
intl
json
libxml
mbstring
mcrypt
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
pdlib
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```

**Comment by matiasdelellis** [comment]
D'OH!
![imagen](https://user-images.githubusercontent.com/733715/224451327-724800e3-e10a-4168-9e63-b4708eeae9e7.png)

Since it's a feature I don't use, I never noticed it. I'll fix it soon...

Excuse me, 😞

**Comment by jaythie** [comment]
I have the same Problem, It worked once or twice already though. i just cant seem to update them because of said error.

Your app ist still amazing. :)

**Comment by Tirpitz93** [comment]
For me it now works when specifying a user but throws this error when running without argument (all users)

```
occ face:sync-albums
Synchronizing albums for the user <>. An unhandled exception has been thrown:
TypeError: OCA\FaceRecognition\Helper\PhotoAlbums::syncUser(): Argument #1 ($userId) must be of type string, null given, called in /var/www/html/nextcloud/apps/facerecognition/lib/Command/SyncAlbumsCommand.php on line 119 and defined in /var/www/html/nextcloud/apps/facerecognition/lib/Helper/PhotoAlbums.php:67
Stack trace:
#0 /var/www/html/nextcloud/apps/facerecognition/lib/Command/SyncAlbumsCommand.php(119): OCA\FaceRecognition\Helper\PhotoAlbums->syncUser()
#1 /var/www/html/nextcloud/apps/recognize/vendor/symfony/console/Command/Command.php(298): OCA\FaceRecognition\Command\SyncAlbumsCommand->execute()
#2 /var/www/html/nextcloud/apps/recognize/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#3 /var/www/html/nextcloud/apps/recognize/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#4 /var/www/html/nextcloud/apps/recognize/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#5 /var/www/html/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run()
#6 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#7 /var/www/html/nextcloud/occ(11): require_once('...')
#8 {main}

```

**Comment by Tirpitz93** [comment]
Currently using the following script as a workaround:
```
cd  "/var/www/html/nextcloud"

#mapfile -t users < <( php occ users:list| read a)
for user in $(php occ user:list  | awk '{print $3}') ; do
  echo "Syncing albums for ${user}"
  php occ face:sync-albums -u $user
  echo "Done syncing almbums for $user"
done

php occ recognize:cluster


```

**Comment by matiasdelellis** [comment]
Fixed on v0.9.12. Thank you for reporting it. 😄

**Comment by xkill** [comment]
> Fixed on v0.9.12. Thank you for reporting it. smile

Thank you for fixing it ;)

**Comment by EagleWolfpack** [comment]
Sorry, but it seems under 0.9.31 the problem is back
Synchronizing albums for the user <>. An unhandled exception has been thrown:
TypeError: OCA\FaceRecognition\Helper\PhotoAlbums::syncUser(): Argument #1 ($userId) must be of type string, null given, called in /var/www/nextcloud/apps/facerecognition/lib/Command/SyncAlbumsCommand.php on line 119 and defined in /var/www/nextcloud/apps/facerecognition/lib/Helper/PhotoAlbums.php:67
Stack trace:
#0 /var/www/nextcloud/apps/facerecognition/lib/Command/SyncAlbumsCommand.php(119): OCA\FaceRecognition\Helper\PhotoAlbums->syncUser()
#1 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\FaceRecognition\Command\SyncAlbumsCommand->execute()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#5 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#6 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#7 /var/www/nextcloud/occ(11): require_once('...')
